name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
       LISP: sbcl-bin

    steps:
    - uses: actions/checkout@v1
    - uses: 40ants/setup-lisp@v2
    - name: update and install system dependencies
      run: |
        sudo apt-get -qq update | true
        sudo apt-get -qq install libmpfr6 libmpfr-dev
    - uses: 40ants/run-tests@v2
      with:
        asdf-system: hypergeometrica
