name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: instal host sbcl
      run: |
        sudo apt-get -qq update | true
        sudo apt-get -qq install sbcl
    - name: install quicklisp
      run: |
        sbcl --no-sysinit --no-userinit --load .github/workflows/files/ql.lisp --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' --eval '(ql::without-prompting (ql:add-to-init-file))' --non-interactive
    - name: setup package
      run: |
        ln -s $PWD ~/.quicklisp/local-projects/hypergeometrica
        sbcl --eval '(ql:quickload "hypergeometrica")' --non-interactive
    - name: run a single function from package
      run: |
        sbcl --eval "(asdf:load-system :hypergeometrica)" --eval "(in-package :hypergeometrica)" --eval "(partial-digits (binary-split (make-e-series) 0 100) 50)" --non-interactive
    - name: run tests
      run: |
        sbcl --eval '(ql:quickload "fiasco")' --eval "(asdf:test-system :hypergeometrica)" --non-interactive
